---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /runtime
      - /prisma

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: codepod-ingress
spec:
  {{- if .Values.tls.enabled }}
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Values.tls.secretName }}
  {{- end }}
  routes:
  - match: "Host(`{{ .Values.hostname }}`) && PathPrefix(`/`)"
    kind: Rule
    services:
      - name: codepod-ui-service
        port: 80
  - match: "Host(`{{ .Values.hostname }}`) && PathPrefix(`/graphql`)"
    kind: Rule
    services:
      - name: codepod-api-service
        port: 4000
  - match: "Host(`{{ .Values.hostname }}`) && PathPrefix(`/runtime`)"
    kind: Rule
    middlewares:
      - name: stripprefix
    services:
      - name: codepod-proxy-service
        port: 4010

{{- if .Values.tls.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-to-https
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.hostname }}`)"
      kind: Rule 
      # We need this services clause to make the route valid.
      services:
        - name: codepod-ui-service
          port: 80
      middlewares:
        - name: redirect-https
{{- end }}
