---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alpha-codepod-io
spec:
  secretName: alpha-codepod-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "alpha.codepod.io"
  dnsNames:
  - "alpha.codepod.io"
