-- CreateTable
CREATE TABLE "_STAR" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "_STAR_AB_unique" ON "_STAR"("A", "B");

-- CreateIndex
CREATE INDEX "_STAR_B_index" ON "_STAR"("B");

-- AddForeignKey
ALTER TABLE "_STAR" ADD CONSTRAINT "_STAR_A_fkey" FOREIGN KEY ("A") REFERENCES "Repo"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_STAR" ADD CONSTRAINT "_STAR_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
