apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret
data:
  POSTGRES_USER: your-base64-encrypted
  POSTGRES_PASSWORD: your-base64-encrypted
  POSTGRES_DB: your-base64-encrypted
  JWT_SECRET: your-base64-encrypted
