apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
  labels:
    app: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
    spec:
      containers:
        - name: data-migrations
          image: lihebi/codepod-api:v0.4.3-alpha.3
          # Run this manually on-demand: npx prisma migrate dev --name init
          # Or do a reset: npx prisma db push
          command: ["npx", "prisma", "studio"]
          ports:
            - containerPort: 5555
          env:
            - name: DATABASE_URL
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: prisma-service
spec:
  ports:
    - port: 80
      targetPort: 5555
      protocol: TCP
  selector:
    app: prisma
