# UI

apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepod-ui-deployment
  labels:
    app: codepod-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codepod-ui
  template:
    metadata:
      labels:
        app: codepod-ui
    spec:
      containers:
        - name: codepod-ui
          image: lihebi/codepod-ui:v0.4.3-alpha.3
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: codepod-ui-service
spec:
  selector:
    app: codepod-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# API
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepod-api-deployment
  labels:
    app: codepod-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codepod-api
  template:
    metadata:
      labels:
        app: codepod-api
    spec:
      serviceAccountName: api-account
      containers:
        - name: codepod-api
          image: lihebi/codepod-api:v0.4.3-alpha.3
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "<YOUR_DATABASE_URL>"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: JWT_SECRET
            - name: PROXY_API_URL
              value: "http://codepod-proxy-service:4011/graphql"
            - name: ZMQ_KERNEL_IMAGE
              value: "lihebi/codepod-kernel-python:v0.4.3-alpha.3"
            - name: WS_RUNTIME_IMAGE
              value: "lihebi/codepod-runtime:v0.4.3-alpha.3"
            - name: RUNTIME_SPAWNER
              value: k8s
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: codepod-api-service
spec:
  selector:
    app: codepod-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

# Proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepod-proxy-deployment
  labels:
    app: codepod-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codepod-proxy
  template:
    metadata:
      labels:
        app: codepod-proxy
    spec:
      containers:
        - name: codepod-proxy
          image: lihebi/codepod-proxy:v0.4.3-alpha.3
          ports:
            - containerPort: 4010
            - containerPort: 4011
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: codepod-proxy-service
spec:
  selector:
    app: codepod-proxy
  ports:
    - name: proxy-port
      protocol: TCP
      port: 4010
      targetPort: 4010
    - name: api-port
      protocol: TCP
      port: 4011
      targetPort: 4011
