# Use postgres/example user/password credentials
version: "3.5"

services:
  api:
    image: node:18
    working_dir: /codepod/apps/desktop-api
    ports:
      - 4001:4001
    volumes:
      - ../..:/codepod
      - desktop-var-codepod:/var/codepod
    command: sh -c "npm run dev"

  yjs:
    image: node:18
    working_dir: /codepod/apps/desktop-yjs
    ports:
      - 4234:4233
    volumes:
      - ../..:/codepod
      - desktop-var-codepod:/var/codepod
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "npm run dev"

  ui:
    image: node:18
    working_dir: /codepod/apps/desktop-ui
    ports:
      - 3001:3001
    environment:
      VITE_APP_YJS_WS_URL: "ws://localhost:4234/socket"
      VITE_APP_API_URL: "http://localhost:4001/graphql"
      # Native spawner
      VITE_APP_SPAWNER_API_URL: "http://localhost:4022/graphql"
      # Docker spawner
      # VITE_APP_SPAWNER_API_URL: "http://localhost:4021/graphql"
    volumes:
      - ../..:/codepod
    command: sh -c "npm run dev"

volumes:
  desktop-var-codepod:

networks:
  default:
    name: codepod
    driver: bridge
