const spec = {
  nodes: {
    tableControllerCell: {
      atom: true,
      isolating: true,
      content: "block*",
      attrs: {
        colspan: { default: 1 },
        rowspan: { default: 1 },
        colwidth: { default: null },
        background: { default: null },
      },
      tableRole: "header_cell",
      parseDOM: [{ tag: "th[data-controller-cell]" }],
      allowGapCursor: false,
    },
    doc: { attrs: {}, content: "block+" },
    text: { group: "inline" },
    paragraph: {
      content: "inline*",
      draggable: false,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "p" }],
      group: "lastNodeCompatible textBlock block formattingNode",
    },
    table: {
      isolating: true,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
        isControllersInjected: { default: false },
        insertButtonAttrs: { default: null },
      },
      content: "tableRow+",
      tableRole: "table",
      parseDOM: [{ tag: "table" }],
      allowGapCursor: false,
      group: "block",
    },
    math_inline: {
      group: "math inline",
      content: "text*",
      inline: true,
      atom: true,
      attrs: {},
      parseDOM: [{ tag: "math-inline" }, { tag: "span" }],
    },
    math_display: {
      group: "block math block",
      content: "text*",
      atom: true,
      code: true,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "math-display" }, { tag: "dl" }],
    },
    image: {
      inline: true,
      draggable: true,
      selectable: false,
      attrs: {
        alt: { default: "" },
        crop: { default: null },
        height: { default: null },
        width: { default: null },
        rotate: { default: null },
        src: { default: null },
        title: { default: "" },
        fileName: { default: null },
        resizable: { default: false },
      },
      parseDOM: [{ tag: "img[src]" }],
      group: "inline media",
    },
    horizontalRule: {
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "hr" }],
      group: "block",
    },
    blockquote: {
      content: "block+",
      defining: true,
      draggable: false,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "blockquote", priority: 100 }],
      group: "block formattingNode",
    },
    codeBlock: {
      content: "text*",
      marks: "",
      defining: true,
      isolating: true,
      draggable: false,
      code: true,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
        language: { default: "markup" },
        wrap: { default: false },
      },
      //   parseDOM: [
      //     { tag: "div.highlight", preserveWhitespace: "full" },
      //     { tag: "pre", preserveWhitespace: "full" },
      //   ],
      group: "block code",
    },
    heading: {
      content: "inline*",
      defining: true,
      draggable: false,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
        level: { default: 1 },
      },
      parseDOM: [
        { tag: "h1" },
        { tag: "h2" },
        { tag: "h3" },
        { tag: "h4" },
        { tag: "h5" },
        { tag: "h6" },
      ],
      group: "block textBlock formattingNode",
    },
    iframe: {
      selectable: false,
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
        src: {},
        allowFullScreen: { default: true },
        frameBorder: { default: 0 },
        type: { default: "custom" },
        width: { default: null },
        height: { default: null },
      },
      parseDOM: [{ tag: "iframe" }],
      group: "block",
    },
    bulletList: {
      content: "listItem+",
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "ul" }],
      group: "block listContainer",
    },
    orderedList: {
      content: "listItem+",
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
        order: { default: 1 },
      },
      parseDOM: [{ tag: "ol" }],
      group: "block listContainer",
    },
    taskList: {
      content: "taskListItem+",
      attrs: {
        dir: { default: null },
        ignoreBidiAutoUpdate: { default: null },
      },
      parseDOM: [{ tag: "ul[data-task-list]", priority: 1000 }],
      group: "block listContainer",
    },
    taskListItem: {
      content: "paragraph block*",
      defining: true,
      draggable: false,
      attrs: { checked: { default: false } },
      parseDOM: [{ tag: "li[data-task-list-item]", priority: 1000 }],
      group: "listItemNode",
    },
    emoji: {
      selectable: true,
      draggable: false,
      inline: true,
      atom: true,
      attrs: { code: {} },
      parseDOM: [{ tag: "span[data-remirror-emoji" }],
      group: "inline",
    },
    tableRow: {
      attrs: {},
      content: "(tableCell | tableHeaderCell | tableControllerCell)*",
      tableRole: "row",
      parseDOM: [{ tag: "tr" }],
      allowGapCursor: false,
    },
    tableCell: {
      isolating: true,
      content: "block+",
      attrs: {
        colspan: { default: 1 },
        rowspan: { default: 1 },
        colwidth: { default: null },
        background: { default: null },
      },
      tableRole: "cell",
      parseDOM: [{ tag: "td" }],
      allowGapCursor: false,
    },
    tableHeaderCell: {
      isolating: true,
      content: "block+",
      attrs: {
        colspan: { default: 1 },
        rowspan: { default: 1 },
        colwidth: { default: null },
        background: { default: null },
      },
      tableRole: "header_cell",
      parseDOM: [{ tag: "th" }],
      allowGapCursor: false,
    },
    hardBreak: {
      inline: true,
      selectable: false,
      atom: true,
      attrs: {},
      parseDOM: [{ tag: "br" }],
      group: "inline",
    },
    listItem: {
      content: "paragraph block*",
      defining: true,
      draggable: false,
      attrs: {
        closed: { default: false },
        nested: { default: false },
      },
      parseDOM: [{ tag: "li", priority: 0 }],
      group: "listItemNode",
    },
  },
  marks: {
    link: {
      inclusive: false,
      excludes: "_",
      attrs: {
        href: {},
        target: { default: null },
        auto: { default: false },
      },
      parseDOM: [{ tag: "a[href]" }],
      group: "link excludeFromInputRules",
    },
    textHighlight: {
      attrs: { highlight: { default: "" } },
      parseDOM: [
        { tag: "span[data-text-highlight-mark]" },
        { tag: "span[data-text-highlight-mark]" },
        { style: "background-color", priority: 10 },
      ],
      group: "formattingMark fontStyle",
    },
    sup: {
      attrs: {},
      parseDOM: [{ tag: "sup" }],
      group: "formattingMark fontStyle",
    },
    sub: {
      attrs: {},
      parseDOM: [{ tag: "sub" }],
      group: "formattingMark fontStyle",
    },
    bold: {
      attrs: {},
      parseDOM: [{ tag: "strong" }, { tag: "b" }, { style: "font-weight" }],
      group: "formattingMark fontStyle",
    },
    code: {
      excludes: "_",
      attrs: {},
      parseDOM: [{ tag: "code" }],
      group: "code excludeFromInputRules",
    },
    strike: {
      attrs: {},
      parseDOM: [
        { tag: "s" },
        { tag: "del" },
        { tag: "strike" },
        { style: "text-decoration" },
      ],
      group: "fontStyle formattingMark",
    },
    italic: {
      attrs: {},
      parseDOM: [{ tag: "i" }, { tag: "em" }, { style: "font-style=italic" }],
      group: "fontStyle formattingMark",
    },
    underline: {
      attrs: {},
      parseDOM: [{ tag: "u" }, { style: "text-decoration" }],
      group: "fontStyle formattingMark",
    },
  },
};

export default spec;
